### ISSUE TITLE
Actual '{' char

### ISSUE THREAD

**Issue by rizo** [AriaFallah/ppx_str#1]
Am I correct in assuming that there's currently no way to write the actual `{` and `}` symbols inside a interpolated string?

**Comment by AriaFallah** [comment]
You can use them, but with caveats. See here: https://regex101.com/r/NFMJVw/1

We can fix this in two ways:

1. Use `${}` like js instead of just `{}`
2. Build in escaping of {} like `\{\}`

I like 2 the most because I've never been a fan of the `$` in front, and you would use `\{text inside curly that's not supposed to be interpolated\}` very rarely. 1 would be better if I wanted to support records or anything with `{}` inside of the interpolated string though, but idk if we wanna do that because it encourages putting overly complex stuff in the string.

**Comment by AriaFallah** [comment]
https://github.com/AriaFallah/ppx_str/commit/98f1bfe759e58b31a5336602f2b79dee27804f59 addresses this. Needs some more testing, but it's on the right track.

**Comment by rizo** [comment]
Thanks! Looks very good, I'll start using this in one of my projects to test it.

**Comment by AriaFallah** [comment]
@rizo also...there's a bug already lol, and I still need to put this on opam. Is there any resource I could use for extensively testing the lexer?

**Comment by AriaFallah** [comment]
@rizo okay https://github.com/AriaFallah/ppx_str/commit/e40d89761a94cedd1e625ea6c5f9b17cfe8ba28e should actually be good now

**Comment by rizo** [comment]
You can try setting up [qcheck](https://github.com/c-cube/qcheck) and randomly generate inputs. But I'd suggest starting with something simpler like [alcotest](https://github.com/mirage/alcotest/) and manually writing test cases.

**Comment by rizo** [comment]
I also have a couple of other ideas inspired by [ppx_custom_printf](https://github.com/janestreet/ppx_custom_printf).

### Shorter syntax

The `[%str "..."]` is kind of verbose, how about `!"..."`? You can intercept the `!` followed by a string literal and process the content. Example:

```ocaml
!"Hello, {name}."
```

### Custom formatters

I think it would be great to be able to use pretty printers from say [Fmt](http://erratique.ch/software/fmt/doc/Fmt.html). For example:

```ocaml
!"Hello, I'm {name}. I'm {age: Fmt.int} years old."
```

This would be translated into something like:

```ocaml
Format.asprintf "Hello, I'm %s. I'm %a years old" name Fmt.int age
```

It could generate `String.concat` somehow for better performance.

---

Just writing this here because I've been thinking about it lately. I would like to know what you think. I'd be glad to contribute if you think this could be useful.

**Comment by rizo** [comment]
The syntax for custom formatters is particularly useful for compound types, eg:

```ocaml
let fruits = ["Apple"; "Banana"; "Peach"] in
!"This is a list of fruits: {fruits: list string}."
```

Where `list string` could be translated to `Fmt.(list string)`.

**Comment by AriaFallah** [comment]
@rizo 

1\. Regarding `[%str ""] -> !`, I'm actually against it. I like how explicit it is that you're using a PPX, and the overhead of typing `[%str ""]` is worthwhile.

2\. The formatting is definitely something to think about. Right now we technically support a more verbose version of this anyways since we allow arbitrary expressions in the curly braces i.e.

```ocaml
{Fmt.(list string) fruits}
```
so I'm curious how big of a win it is to create something custom. You can open another issue for the custom formatting if you disagree, and we could track this there.

**Comment by rizo** [comment]
`[%str "{Fmt.(list string) fruits}"` is not going to work actually. Formatters do not produce string output directly, they operate in a more general way. I believe it would require a syntax transformation to get a more readable version.

**Comment by AriaFallah** [comment]
Ah ok I was unfamiliar with the library so I assumed it went straight to being a string.

**Comment by AriaFallah** [comment]
@rizo Update on this is that I dropped sedlexing (I was mostly using it out interest rather than it fulfilling my needs) and wrote my own parser that handles escaping `{` and nested `{` and other things.
